-- NERO · semente de regras clínicas · versão 2026.1 · revisada em 2026-09-15
-- Gerada a partir das decisões C-001–C-009 (docs/nero/02-DECISOES.md) e do acervo docs/nero/referencias/.
-- Cada linha cita a fonte e, quando existe, o número da recomendação.
insert into public.regras_clinicas
  (modulo, programa, exame_tipo, condicao, classificacao, nivel_alerta, proxima_acao, intervalo_meses, mensagem_paciente, fonte, ano, versao, revisada_em)
values
('rastreando','mama',null,'{"idade_min": 40, "idade_max": 74}','normal','verde','Mamografia anual',12,'Você está na faixa etária de rastreamento: mamografia anual dos 40 aos 74 anos.','CBR/SBM/FEBRASGO 2023 (Urban et al.) · Nota Técnica CNM 2025',2023,'2026.1','2026-09-15'),
('rastreando','mama','mamografia','{"birads": 0}','pendente','cinza','Complementar o exame',null,'Sua mamografia precisa de complementação (BI-RADS 0) antes de um resultado final. Procure o serviço que realizou o exame.','ACR BI-RADS · §44',2023,'2026.1','2026-09-15'),
('rastreando','mama','mamografia','{"birads": 1}','normal','verde','Nova mamografia em 12 meses',12,'Sua mamografia não apresentou achados suspeitos (BI-RADS 1). Seu próximo rastreamento foi programado. Consulte seu médico para orientações.','ACR BI-RADS · CBR/SBM/FEBRASGO 2023 (Urban et al.) · Nota Técnica CNM 2025',2023,'2026.1','2026-09-15'),
('rastreando','mama','mamografia','{"birads": 2}','normal','verde','Nova mamografia em 12 meses',12,'Sua mamografia mostrou achados benignos (BI-RADS 2). Seu próximo rastreamento foi programado.','ACR BI-RADS · CBR/SBM/FEBRASGO 2023 (Urban et al.) · Nota Técnica CNM 2025',2023,'2026.1','2026-09-15'),
('rastreando','mama','mamografia','{"birads": 3}','controle','amarelo','Controle de curto intervalo',6,'Achado provavelmente benigno (BI-RADS 3): a recomendação habitual é controle em 6 meses, ou no intervalo indicado no seu laudo. Consulte seu médico.','ACR BI-RADS (categoria 3) · C-009',2023,'2026.1','2026-09-15'),
('rastreando','mama','mamografia','{"birads": 4}','investigacao','laranja','Avaliação médica para investigação',null,'Seu exame apresentou um achado que necessita investigação complementar (BI-RADS 4). Procure o profissional responsável para definir a próxima etapa.','ACR BI-RADS · §44',2023,'2026.1','2026-09-15'),
('rastreando','mama','mamografia','{"birads": 5}','especializado','vermelho','Avaliação especializada prioritária',null,'Seu exame apresentou um achado que merece avaliação especializada prioritária (BI-RADS 5). Entre em contato com o profissional responsável ou serviço de referência.','ACR BI-RADS · §44',2023,'2026.1','2026-09-15'),
('rastreando','mama','mamografia','{"birads": 6}','especializado','vermelho','Acompanhamento especializado',null,'Este exame indica acompanhamento especializado (BI-RADS 6). As próximas etapas são definidas pela sua equipe de tratamento.','ACR BI-RADS · §44',2023,'2026.1','2026-09-15'),
('rastreando','colo_utero',null,'{"idade_min": 25, "idade_max": 64}','normal','verde','Teste de DNA-HPV a cada 5 anos',60,'Você está na faixa de rastreamento do colo do útero: teste de DNA-HPV a partir dos 25 anos, repetido a cada 5 anos quando negativo.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 1, 12, 18',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "negativo", "imunossuprimida": false}','normal','verde','Novo teste em 5 anos',60,'Não foi detectado HPV oncogênico. Seu próximo rastreamento foi programado para daqui a 5 anos.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 18/23',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "negativo", "imunossuprimida": true}','normal','verde','Novo teste em 3 anos',36,'Não foi detectado HPV oncogênico. Em situação de imunossupressão, o intervalo recomendado é de 3 anos.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 39',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "invalido"}','pendente','cinza','Nova coleta para repetir o teste',null,'O teste não pôde ser lido (resultado inválido). É necessária nova coleta com o profissional de saúde.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 21',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "16_18"}','investigacao','laranja','Colposcopia',null,'Foi detectado um tipo de HPV associado a maior risco de lesões do colo do útero (16 ou 18). Procure seu médico para a avaliação complementar (colposcopia).','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 19',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "imunossuprimida": true}','investigacao','laranja','Colposcopia',null,'Foi detectado HPV oncogênico. Em situação de imunossupressão, a diretriz recomenda colposcopia independentemente da citologia. Procure seu médico.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 40',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "negativa", "imunossuprimida": false}','controle','amarelo','Repetir o teste de DNA-HPV em 12 meses',12,'HPV oncogênico (não 16/18) com citologia normal: a diretriz recomenda repetir o teste de DNA-HPV em 12 meses. Consulte seu médico.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 22',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "persistente_24m"}','investigacao','laranja','Colposcopia',null,'O HPV oncogênico persiste após 24 meses de acompanhamento. A diretriz recomenda colposcopia, independentemente da citologia. Procure seu médico.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 25',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "insatisfatoria", "imunossuprimida": false}','investigacao','laranja','Colposcopia',null,'A citologia reflexa não pôde ser avaliada (amostra insatisfatória): a diretriz recomenda colposcopia. Procure seu médico.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "asc_us", "imunossuprimida": false}','investigacao','laranja','Colposcopia',null,'HPV oncogênico com alteração na citologia: a diretriz recomenda colposcopia. Procure seu médico.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "lsil", "imunossuprimida": false}','investigacao','laranja','Colposcopia',null,'HPV oncogênico com alteração na citologia: a diretriz recomenda colposcopia. Procure seu médico.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "asc_h", "imunossuprimida": false}','especializado','vermelho','Colposcopia',null,'Seu exame apresentou um achado que necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "hsil", "imunossuprimida": false}','especializado','vermelho','Colposcopia',null,'Seu exame apresentou um achado que necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "agc", "imunossuprimida": false}','especializado','vermelho','Colposcopia',null,'Seu exame apresentou um achado que necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "ais", "imunossuprimida": false}','especializado','vermelho','Colposcopia',null,'Seu exame apresentou um achado que necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','dna_hpv','{"hpv": "outros_oncogenicos", "citologia_reflexa": "suspeita_malignidade", "imunossuprimida": false}','especializado','vermelho','Colposcopia',null,'Seu exame apresentou um achado que necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 20',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "negativa"}','normal','verde','Repetir conforme protocolo (anual; trienal após 2 normais)',12,'Citologia sem alterações. Onde o DNA-HPV ainda não está disponível, repete-se anualmente e, após dois exames normais seguidos, a cada 3 anos.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 28 · C-003',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "insatisfatoria"}','pendente','cinza','Repetir a coleta',null,'A amostra não permitiu avaliação adequada. Repita o exame conforme orientação do profissional.','INCA 2016 — Diretrizes rastreamento (citologia) · transição: INCA 2025 Rec. 26–28 [validar no texto de 2016 — a obter]',2016,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "asc_us"}','controle','amarelo','Repetir a citologia no intervalo indicado pelo médico',6,'Alteração de significado indeterminado (ASC-US): em geral repete-se a citologia em 6 meses (12 meses antes dos 30 anos). Consulte seu médico.','INCA 2016 — Diretrizes rastreamento (citologia) · transição: INCA 2025 Rec. 26–28 [validar no texto de 2016 — a obter]',2016,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "lsil"}','controle','amarelo','Repetir a citologia no intervalo indicado pelo médico',6,'Lesão de baixo grau (LSIL): em geral repete-se a citologia em 6 meses (12 meses antes dos 25 anos). Consulte seu médico.','INCA 2016 — Diretrizes rastreamento (citologia) · transição: INCA 2025 Rec. 26–28 [validar no texto de 2016 — a obter]',2016,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "asc_h"}','especializado','vermelho','Colposcopia',null,'Seu exame necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 26 · §45.7',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "hsil"}','especializado','vermelho','Colposcopia',null,'Seu exame necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 26 · §45.7',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "agc"}','especializado','vermelho','Colposcopia',null,'Seu exame necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 26 · §45.7',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "ais"}','especializado','vermelho','Colposcopia',null,'Seu exame necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 26 · §45.7',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','citologia','{"citologia": "suspeita_malignidade"}','especializado','vermelho','Colposcopia',null,'Seu exame necessita avaliação profissional com prioridade (colposcopia). Procure o responsável para definir a próxima etapa.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed. Rec. 26 · §45.7',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','colposcopia','{"achado": "normal"}','controle','amarelo','Seguimento conforme o médico',12,'Colposcopia sem alterações. O seguimento é definido pelo seu médico conforme o teste que motivou o exame.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed.',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','colposcopia','{"achado": "nic1"}','controle','amarelo','Seguimento conforme o médico',12,'Lesão de baixo grau (NIC 1): geralmente acompanhada, não tratada. Seu médico define o intervalo.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed.',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','colposcopia','{"achado": "nic2"}','especializado','vermelho','Acompanhamento especializado',null,'As próximas etapas são definidas pela sua equipe.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed.',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','colposcopia','{"achado": "nic3"}','especializado','vermelho','Acompanhamento especializado',null,'As próximas etapas são definidas pela sua equipe.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed.',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','colposcopia','{"achado": "ais"}','especializado','vermelho','Acompanhamento especializado',null,'As próximas etapas são definidas pela sua equipe.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed.',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','colposcopia','{"achado": "carcinoma"}','especializado','vermelho','Acompanhamento especializado',null,'As próximas etapas são definidas pela sua equipe.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed.',2025,'2026.1','2026-09-15'),
('rastreando','colo_utero','colposcopia','{"achado": "inconclusiva"}','pendente','cinza','Complementar a avaliação',null,'A colposcopia foi inconclusiva. Procure o profissional para complementar a avaliação.','INCA 2025 — Diretrizes Rastreamento Colo do Útero, 3. ed.',2025,'2026.1','2026-09-15'),
('rastreando','colorretal',null,'{"idade_min": 50, "idade_max": 74}','normal','verde','FIT a cada 2 anos',24,'Você está na faixa de rastreamento colorretal: teste imunoquímico fecal (FIT) a cada 2 anos, dos 50 aos 74 anos.','CONITEC 2026 — Diretrizes Rastreamento Cólon e Reto (aprovada 23/06/2026) Rec. 5, 6, 7',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','fit','{"fit": "negativo"}','normal','verde','Novo FIT em 2 anos',24,'Seu teste não identificou sangue oculto nas fezes. Seu próximo rastreamento foi programado.','CONITEC 2026 — Diretrizes Rastreamento Cólon e Reto (aprovada 23/06/2026) Rec. 7',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','fit','{"fit": "positivo"}','investigacao','laranja','Colonoscopia',null,'Seu teste deu positivo. Isso não significa câncer, mas é necessária investigação com colonoscopia. Procure seu médico.','CONITEC 2026 — Diretrizes Rastreamento Cólon e Reto (aprovada 23/06/2026) Rec. 8',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "normal", "qualidade_adequada": true}','normal','verde','Nova colonoscopia em 10 anos; sem FIT nesse período',120,'Colonoscopia completa e sem alterações: a recomendação é repetir só em 10 anos, sem necessidade de FIT nesse intervalo, se você seguir sem sintomas.','CONITEC 2026 — Diretrizes Rastreamento Cólon e Reto (aprovada 23/06/2026) texto da Rec. 8',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "incompleta"}','pendente','cinza','Completar o exame',null,'A colonoscopia foi incompleta. Procure o profissional para completar a avaliação.','§47',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "polipos", "histopatologico": "aguardando"}','pendente','cinza','Aguardar o histopatológico',null,'Foram removidos pólipos. Registre o resultado do histopatológico quando disponível para o NERO definir o seguimento.','§47',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "polipos", "histopatologico": "hiperplasico"}','normal','verde','Nova colonoscopia em 10 anos',120,'Pólipo hiperplásico não aumenta o risco. O seguimento segue o habitual.','§47 · ACG 2021',2021,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "polipos", "histopatologico": "adenoma"}','controle','amarelo','Colonoscopia de controle no intervalo do laudo',null,'Adenoma removido: o intervalo de controle depende do número e tamanho dos pólipos e é definido pelo seu médico. Registre o intervalo indicado no laudo.','§47',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "polipos", "histopatologico": "adenoma_avancado"}','controle','amarelo','Colonoscopia de controle no intervalo do laudo',null,'Adenoma avançado removido: o controle costuma ser mais próximo e é definido pelo seu médico. Registre o intervalo indicado no laudo.','§47',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "polipos", "histopatologico": "carcinoma"}','especializado','vermelho','Acompanhamento especializado',null,'As próximas etapas são definidas pela sua equipe.','§47',2026,'2026.1','2026-09-15'),
('rastreando','colorretal','colonoscopia','{"achado": "massa_suspeita"}','especializado','vermelho','Avaliação especializada prioritária',null,'Foi identificada uma lesão que precisa de avaliação especializada prioritária. Entre em contato com o profissional responsável.','§47',2026,'2026.1','2026-09-15'),
('rastreando','pulmao',null,'{"idade_min": 50, "idade_max": 80}','normal','verde','TCBD anual',12,'Você atende aos critérios de rastreamento de câncer de pulmão: tomografia de baixa dose anual.','USPSTF 2021 (Grau B), endossada pela SBPT',2021,'2026.1','2026-09-15'),
('rastreando','pulmao','tcbd','{"lungrads": "0"}','pendente','cinza','Complementar (comparação com exame prévio ou TC em 1–3 meses)',null,'O exame precisa de complementação (Lung-RADS 0). Siga a orientação do laudo e do profissional.','ACR Lung-RADS v2022',2022,'2026.1','2026-09-15'),
('rastreando','pulmao','tcbd','{"lungrads": "1"}','normal','verde','TCBD em 12 meses',12,'Resultado negativo (Lung-RADS 1). Próxima tomografia em 12 meses.','ACR Lung-RADS v2022',2022,'2026.1','2026-09-15'),
('rastreando','pulmao','tcbd','{"lungrads": "2"}','normal','verde','TCBD em 12 meses',12,'Achado de comportamento benigno (Lung-RADS 2). Próxima tomografia em 12 meses.','ACR Lung-RADS v2022',2022,'2026.1','2026-09-15'),
('rastreando','pulmao','tcbd','{"lungrads": "3"}','controle','amarelo','TCBD em 6 meses',6,'Achado provavelmente benigno (Lung-RADS 3). Controle em 6 meses. Consulte seu médico.','ACR Lung-RADS v2022',2022,'2026.1','2026-09-15'),
('rastreando','pulmao','tcbd','{"lungrads": "4A"}','investigacao','laranja','TCBD em 3 meses (PET/CT a critério médico)',3,'Foi identificado um achado que necessita avaliação mais próxima (Lung-RADS 4A). Siga a recomendação do laudo e do profissional.','ACR Lung-RADS v2022',2022,'2026.1','2026-09-15'),
('rastreando','pulmao','tcbd','{"lungrads": "4B"}','especializado','vermelho','Avaliação especializada prioritária',null,'Este resultado merece avaliação especializada prioritária. Entre em contato com o profissional responsável.','ACR Lung-RADS v2022',2022,'2026.1','2026-09-15'),
('rastreando','pulmao','tcbd','{"lungrads": "4X"}','especializado','vermelho','Avaliação especializada prioritária',null,'Este resultado merece avaliação especializada prioritária. Entre em contato com o profissional responsável.','ACR Lung-RADS v2022',2022,'2026.1','2026-09-15'),
('rastreando','prostata',null,'{"idade_min": 50, "idade_max": 75}','normal','verde','Conversar com o médico sobre o rastreamento',null,'Você está na faixa em que as sociedades brasileiras recomendam conversar com um profissional sobre riscos e benefícios do rastreamento (decisão compartilhada).','Posicionamento SBU/SBOC/SBRT 2023 · Notas SBU 2018/2020',2023,'2026.1','2026-09-15'),
('rastreando','prostata','psa','{"psa_fora_referencia": false}','normal','verde','Repetir conforme orientação do médico',null,'Seu PSA está dentro da referência do laboratório. A periodicidade da repetição é definida pelo seu médico.','Posicionamento SBU/SBOC/SBRT 2023 · Notas SBU 2018/2020 (avaliações periódicas, sem intervalo fixo) · §49',2023,'2026.1','2026-09-15'),
('rastreando','prostata','psa','{"psa_fora_referencia": true}','investigacao','laranja','Avaliação médica recomendada',null,'Seu resultado está fora da faixa de referência informada pelo laboratório. A interpretação do PSA depende de idade, histórico, exame clínico e outros fatores. Converse com seu médico.','§49 · Posicionamento SBU/SBOC/SBRT 2023 · Notas SBU 2018/2020',2023,'2026.1','2026-09-15')
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- NERO · Fase 2 · Coração & Metabolismo · versão 2026.2 · revisada em 2026-09-17
-- Pressão arterial (C-010, C-011). Fontes: DBHA 2025 (Arq Bras Cardiol 2025;122(9):e20250624)
-- e Diretrizes Brasileiras de Medidas da PA Dentro e Fora do Consultório 2023 (Arq Bras Cardiol 2024;121(4):e20240113).
-- Funcionamento: docs/nero/funcionamento/coracao-metabolismo.md §1–§2.
insert into public.regras_clinicas
  (modulo, programa, exame_tipo, condicao, classificacao, nivel_alerta, proxima_acao, intervalo_meses, mensagem_paciente, fonte, ano, versao, revisada_em)
values
('cardio','pressao','pa','{"camada":"implausivel","pad_max":140,"pad_min":40,"pas_min":70,"pas_max":250,"pp_min":20,"pp_max":100}','pendente','cinza','Conferir os valores digitados',null,'Confira os valores digitados. Esta combinação é incomum para uma medida de pressão. Se estiver correta, você pode salvar mesmo assim.','Diretrizes de Medidas da PA 2023, Parte 4 §3 (critérios de exclusão de medidas)',2023,'2026.2','2026-09-17'),
('cardio','pressao','pa','{"camada":"referencia_domiciliar","pas":130,"pad":80}','normal','verde','Nenhuma',null,'Em casa, as diretrizes usam 130/80 como referência para a MRPA. Uma medida isolada não confirma nem afasta hipertensão.','DBHA 2025, Quadro 3.4 · Medidas da PA 2023, Quadro 9 e §3.1 (AMPA é triagem)',2025,'2026.2','2026-09-17'),
('cardio','pressao','pa','{"camada":"convite_mrpa","minimo_medidas":3,"janela_dias":7,"repetir_dias":30,"pas":130,"pad":80}','controle','verde','Sugerir MRPA',null,'Suas medidas em casa vêm ficando acima da referência. As diretrizes recomendam confirmar com uma MRPA. Quer iniciar uma pelo app e conversar com seu médico?','C-010 (gatilho de produto) · DBHA 2025 §3.7.1 (AMPA: triagem para MRPA/MAPA)',2025,'2026.2','2026-09-17'),
('cardio','pressao','pa','{"camada":"muito_elevado","pas":180,"pad":110}','investigacao','laranja','Repouso e repetição da medida',null,'Este valor está muito acima do habitual. Sente-se, descanse 5 minutos e meça de novo. Se você tiver algum dos sintomas a seguir, procure atendimento imediatamente.','DBHA 2025, cap. 11.1 (PAS ≥ 180 e/ou PAD ≥ 110)',2025,'2026.2','2026-09-17'),
('cardio','pressao','pa','{"camada":"muito_elevado_sintoma","pas":180,"pad":110,"sintomas":["dor_toracica","dispneia_importante","deficit_neurologico","alteracao_visual","confusao","sincope"]}','especializado','vermelho','Avaliação imediata em emergência',null,'Pressão muito elevada com esses sintomas pode indicar uma condição que precisa de avaliação urgente. Procure um serviço de emergência agora.','DBHA 2025, cap. 11 (emergência hipertensiva: elevação acentuada com lesão de órgão-alvo)',2025,'2026.2','2026-09-17'),
('cardio','pressao','mrpa','{"camada":"mrpa_acima","pas":130,"pad":80}','controle','amarelo','Levar o relatório ao médico',null,'Suas medidas recentes estão acima do esperado. Considere conversar com seu profissional de saúde. Leve este relatório à consulta.','DBHA 2025, Quadro 3.4 · Medidas da PA 2023, Parte 4 §4 (MRPA anormal ≥ 130 e/ou ≥ 80)',2025,'2026.2','2026-09-17'),
('cardio','pressao','mrpa','{"camada":"validade","minimos":{"4":14,"5":15,"6":18},"medidas_por_periodo":3,"intervalo_min":1,"dias_min":4,"dias_max":6,"dias_padrao":6}','pendente','cinza','Registro insuficiente para interpretação',null,'Esta MRPA não atingiu o número mínimo de medidas para interpretação. O relatório mostra o que foi registrado; converse com seu médico sobre repetir o protocolo.','Medidas da PA 2023, Parte 4 §3 (protocolo 3+3, 4–6 dias) e §5 (mínimos 14/15/18 com manhã e noite em todos os dias)',2023,'2026.2','2026-09-17')
on conflict do nothing;

-- Glicemia (C-012). Fonte: Diretriz da SBD ed. 2026 — Metas de controle glicêmico (R6, Tabela 1, níveis de hipoglicemia);
-- Diagnóstico de DM (R1–R2, Tabela 1); Manejo dos dias de doença no DM1 (Tabela 1); Cetoacidose diabética; Monitorização (R5, R8–R10).
-- Funcionamento: docs/nero/funcionamento/coracao-metabolismo.md §3.
insert into public.regras_clinicas
  (modulo, programa, exame_tipo, condicao, classificacao, nivel_alerta, proxima_acao, intervalo_meses, mensagem_paciente, fonte, ano, versao, revisada_em)
values
('cardio','glicemia','glicemia','{"camada":"metas","perfil":"adulto","jejum":[80,130],"pos":180,"deitar":[90,150]}','normal','verde','Nenhuma',null,'Metas da diretriz da SBD 2026 para adultos e idosos saudáveis: jejum e antes das refeições entre 80 e 130, 2 horas após as refeições abaixo de 180, ao deitar entre 90 e 150. Confirme com seu médico.','SBD 2026 — Metas de controle glicêmico, R6 (IIa, C) e Tabela 1',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"metas","perfil":"idoso_comprometido","jejum":[90,150],"pos":180,"deitar":[100,180]}','normal','verde','Nenhuma',null,'Metas da diretriz da SBD 2026 para idosos com saúde comprometida: jejum e antes das refeições entre 90 e 150, 2 horas após as refeições abaixo de 180, ao deitar entre 100 e 180. Use só se seu médico indicou este enquadramento.','SBD 2026 — Metas de controle glicêmico, Tabela 1',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"metas","perfil":"idoso_muito_comprometido","jejum":[100,180],"pos":null,"deitar":[110,200]}','normal','verde','Nenhuma',null,'Metas da diretriz da SBD 2026 para idosos muito comprometidos: jejum e antes das refeições entre 100 e 180, ao deitar entre 110 e 200, sem meta após as refeições. Use só se seu médico indicou este enquadramento.','SBD 2026 — Metas de controle glicêmico, Tabela 1',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"hipo_n1","min":54,"max":69}','controle','amarelo','Seguir a orientação do médico para hipoglicemia',null,'Sua glicemia está abaixo de 70. Siga a orientação do seu médico para hipoglicemia e meça de novo em seguida. Se tiver sintomas, trate agora.','SBD 2026 — Metas de controle glicêmico (hipoglicemia nível 1: 54–69 mg/dL)',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"hipo_n2","max":53}','investigacao','laranja','Intervenção imediata',null,'Sua glicemia está muito baixa (abaixo de 54). Siga agora a orientação do seu médico para hipoglicemia. Se não melhorar ou tiver confusão, peça ajuda a alguém próximo ou procure atendimento.','SBD 2026 — Metas de controle glicêmico (hipoglicemia nível 2: < 54 mg/dL, exige intervenção imediata)',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"hipo_n3","sintomas":["confusao","precisou_de_ajuda"]}','especializado','vermelho','Atendimento de emergência',null,'Hipoglicemia com confusão ou que precisou da ajuda de outra pessoa é um evento grave. Procure atendimento de emergência agora.','SBD 2026 — Metas de controle glicêmico (hipoglicemia nível 3)',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"hiper","min":251}','investigacao','laranja','Repetir a medida',null,'Sua glicemia está muito alta (acima de 250). Meça de novo e siga a orientação do seu médico. Se você tem diabetes tipo 1 ou usa bomba de insulina, verifique cetonas como seu médico orientou.','SBD 2026 — Manejo dos dias de doença no DM1, Tabela 1 (> 250 mg/dL: checar cetonas)',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"hiper_sintoma","min":251,"sintomas":["nausea","vomito","dor_abdominal","respiracao_rapida","sonolencia"]}','especializado','vermelho','Atendimento de emergência',null,'Glicemia muito alta com esses sintomas precisa de avaliação urgente. Procure um serviço de emergência agora.','SBD 2026 — Diagnóstico e tratamento da cetoacidose diabética (sintomas de CAD)',2026,'2026.2','2026-09-17'),
('cardio','glicemia','glicemia','{"camada":"sem_diabetes","jejum_normal_max":99,"jejum_pre_max":125,"jejum_dm":126,"casual_dm":200}','normal','verde','Conversar com o médico sobre exame de laboratório',null,'Glicemia medida no dedo não faz diagnóstico. A diretriz usa exames de laboratório: jejum abaixo de 100 é normal; entre 100 e 125 é a faixa chamada de pré-diabetes; 126 ou mais, ou 200 ou mais com sintomas, é critério de diabetes. Converse com seu médico sobre fazer um exame de laboratório.','SBD 2026 — Diagnóstico de diabetes mellitus, R1–R2 e Tabela 1',2026,'2026.2','2026-09-17'),
-- Risco cardiovascular (C-013, C-014). Fonte: Diretriz Brasileira de Dislipidemias e Prevenção da Aterosclerose 2025. Funcionamento §4–§5.
('cardio','risco_cv','prevent','{"camada":"categorias","baixo_max":5,"alto_min":20}','normal','verde','Nenhuma',null,'Categoria pelo escore: abaixo de 5% em 10 anos é risco baixo; de 5% a menos de 20% é intermediário; 20% ou mais é alto. A estratificação final é do seu médico, que considera diabetes, LDL, exames de imagem e outros fatores.','Dislipidemias 2025, Tabela 4.1',2025,'2026.2','2026-09-17'),
('cardio','risco_cv','prevent','{"camada":"elegibilidade","idade_min":30,"idade_max":79}','pendente','cinza','Avaliação de risco com o médico',null,'O escore PREVENT foi desenvolvido para pessoas de 30 a 79 anos sem doença cardiovascular conhecida. Fora dessa situação, a avaliação de risco é feita pelo seu médico.','Dislipidemias 2025, §4.2 (30–79 anos, sem DCV prévia), §4.8–4.9',2025,'2026.2','2026-09-17'),
('cardio','risco_cv','cac','{"camada":"cac","alto":100,"percentil_alto":75,"muito_alto":300}','controle','amarelo','Conversar com o médico',null,'A diretriz considera esse valor de escore de cálcio um estratificador de risco cardiovascular. Converse com seu médico sobre o que ele significa para você.','Dislipidemias 2025, Tabela 4.4',2025,'2026.2','2026-09-17'),
('cardio','risco_cv','prevent','{"camada":"dado_recente","pa_mrpa_dias":30,"pa_casual_dias":7,"pa_casual_min":3,"peso_dias":30,"peso_perguntar_dias":90,"lipidios_meses":12,"renal_meses":12,"hba1c_meses":6,"rac_meses":12,"risco_meses":12}','pendente','cinza','Atualizar dados',null,'Alguns dados usados no cálculo têm mais de um ano. O resultado é mostrado, mas vale atualizar seus exames para uma estimativa mais fiel.','C-014 (decisão de produto) · Dislipidemias 2025 (perfil lipídico anual) · DBHA 2025 (reavaliação anual de fatores de risco)',2025,'2026.2','2026-09-17')
on conflict do nothing;
